from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class BooksBookIdPut200ResponseData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, title=None, author=None, published_date=None, publisher=None, price=None, genre=None, description=None):  # noqa: E501
        """BooksBookIdPut200ResponseData - a model defined in OpenAPI

        :param id: The id of this BooksBookIdPut200ResponseData.  # noqa: E501
        :type id: float
        :param title: The title of this BooksBookIdPut200ResponseData.  # noqa: E501
        :type title: str
        :param author: The author of this BooksBookIdPut200ResponseData.  # noqa: E501
        :type author: str
        :param published_date: The published_date of this BooksBookIdPut200ResponseData.  # noqa: E501
        :type published_date: str
        :param publisher: The publisher of this BooksBookIdPut200ResponseData.  # noqa: E501
        :type publisher: str
        :param price: The price of this BooksBookIdPut200ResponseData.  # noqa: E501
        :type price: float
        :param genre: The genre of this BooksBookIdPut200ResponseData.  # noqa: E501
        :type genre: str
        :param description: The description of this BooksBookIdPut200ResponseData.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {
            'id': float,
            'title': str,
            'author': str,
            'published_date': str,
            'publisher': str,
            'price': float,
            'genre': str,
            'description': str
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'author': 'author',
            'published_date': 'publishedDate',
            'publisher': 'publisher',
            'price': 'price',
            'genre': 'genre',
            'description': 'description'
        }

        self._id = id
        self._title = title
        self._author = author
        self._published_date = published_date
        self._publisher = publisher
        self._price = price
        self._genre = genre
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'BooksBookIdPut200ResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _books__bookId__put_200_response_data of this BooksBookIdPut200ResponseData.  # noqa: E501
        :rtype: BooksBookIdPut200ResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> float:
        """Gets the id of this BooksBookIdPut200ResponseData.


        :return: The id of this BooksBookIdPut200ResponseData.
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id: float):
        """Sets the id of this BooksBookIdPut200ResponseData.


        :param id: The id of this BooksBookIdPut200ResponseData.
        :type id: float
        """

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this BooksBookIdPut200ResponseData.


        :return: The title of this BooksBookIdPut200ResponseData.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this BooksBookIdPut200ResponseData.


        :param title: The title of this BooksBookIdPut200ResponseData.
        :type title: str
        """

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this BooksBookIdPut200ResponseData.


        :return: The author of this BooksBookIdPut200ResponseData.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this BooksBookIdPut200ResponseData.


        :param author: The author of this BooksBookIdPut200ResponseData.
        :type author: str
        """

        self._author = author

    @property
    def published_date(self) -> str:
        """Gets the published_date of this BooksBookIdPut200ResponseData.


        :return: The published_date of this BooksBookIdPut200ResponseData.
        :rtype: str
        """
        return self._published_date

    @published_date.setter
    def published_date(self, published_date: str):
        """Sets the published_date of this BooksBookIdPut200ResponseData.


        :param published_date: The published_date of this BooksBookIdPut200ResponseData.
        :type published_date: str
        """

        self._published_date = published_date

    @property
    def publisher(self) -> str:
        """Gets the publisher of this BooksBookIdPut200ResponseData.


        :return: The publisher of this BooksBookIdPut200ResponseData.
        :rtype: str
        """
        return self._publisher

    @publisher.setter
    def publisher(self, publisher: str):
        """Sets the publisher of this BooksBookIdPut200ResponseData.


        :param publisher: The publisher of this BooksBookIdPut200ResponseData.
        :type publisher: str
        """

        self._publisher = publisher

    @property
    def price(self) -> float:
        """Gets the price of this BooksBookIdPut200ResponseData.


        :return: The price of this BooksBookIdPut200ResponseData.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this BooksBookIdPut200ResponseData.


        :param price: The price of this BooksBookIdPut200ResponseData.
        :type price: float
        """

        self._price = price

    @property
    def genre(self) -> str:
        """Gets the genre of this BooksBookIdPut200ResponseData.


        :return: The genre of this BooksBookIdPut200ResponseData.
        :rtype: str
        """
        return self._genre

    @genre.setter
    def genre(self, genre: str):
        """Sets the genre of this BooksBookIdPut200ResponseData.


        :param genre: The genre of this BooksBookIdPut200ResponseData.
        :type genre: str
        """

        self._genre = genre

    @property
    def description(self) -> str:
        """Gets the description of this BooksBookIdPut200ResponseData.


        :return: The description of this BooksBookIdPut200ResponseData.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this BooksBookIdPut200ResponseData.


        :param description: The description of this BooksBookIdPut200ResponseData.
        :type description: str
        """

        self._description = description
