from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class BooksGet200ResponseDataPage(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, current_page=None, total_pages=None, total_books=None, page_size=None):  # noqa: E501
        """BooksGet200ResponseDataPage - a model defined in OpenAPI

        :param current_page: The current_page of this BooksGet200ResponseDataPage.  # noqa: E501
        :type current_page: float
        :param total_pages: The total_pages of this BooksGet200ResponseDataPage.  # noqa: E501
        :type total_pages: float
        :param total_books: The total_books of this BooksGet200ResponseDataPage.  # noqa: E501
        :type total_books: float
        :param page_size: The page_size of this BooksGet200ResponseDataPage.  # noqa: E501
        :type page_size: float
        """
        self.openapi_types = {
            'current_page': float,
            'total_pages': float,
            'total_books': float,
            'page_size': float
        }

        self.attribute_map = {
            'current_page': 'currentPage',
            'total_pages': 'totalPages',
            'total_books': 'totalBooks',
            'page_size': 'pageSize'
        }

        self._current_page = current_page
        self._total_pages = total_pages
        self._total_books = total_books
        self._page_size = page_size

    @classmethod
    def from_dict(cls, dikt) -> 'BooksGet200ResponseDataPage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _books_get_200_response_data_page of this BooksGet200ResponseDataPage.  # noqa: E501
        :rtype: BooksGet200ResponseDataPage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def current_page(self) -> float:
        """Gets the current_page of this BooksGet200ResponseDataPage.


        :return: The current_page of this BooksGet200ResponseDataPage.
        :rtype: float
        """
        return self._current_page

    @current_page.setter
    def current_page(self, current_page: float):
        """Sets the current_page of this BooksGet200ResponseDataPage.


        :param current_page: The current_page of this BooksGet200ResponseDataPage.
        :type current_page: float
        """

        self._current_page = current_page

    @property
    def total_pages(self) -> float:
        """Gets the total_pages of this BooksGet200ResponseDataPage.


        :return: The total_pages of this BooksGet200ResponseDataPage.
        :rtype: float
        """
        return self._total_pages

    @total_pages.setter
    def total_pages(self, total_pages: float):
        """Sets the total_pages of this BooksGet200ResponseDataPage.


        :param total_pages: The total_pages of this BooksGet200ResponseDataPage.
        :type total_pages: float
        """

        self._total_pages = total_pages

    @property
    def total_books(self) -> float:
        """Gets the total_books of this BooksGet200ResponseDataPage.


        :return: The total_books of this BooksGet200ResponseDataPage.
        :rtype: float
        """
        return self._total_books

    @total_books.setter
    def total_books(self, total_books: float):
        """Sets the total_books of this BooksGet200ResponseDataPage.


        :param total_books: The total_books of this BooksGet200ResponseDataPage.
        :type total_books: float
        """

        self._total_books = total_books

    @property
    def page_size(self) -> float:
        """Gets the page_size of this BooksGet200ResponseDataPage.


        :return: The page_size of this BooksGet200ResponseDataPage.
        :rtype: float
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size: float):
        """Sets the page_size of this BooksGet200ResponseDataPage.


        :param page_size: The page_size of this BooksGet200ResponseDataPage.
        :type page_size: float
        """

        self._page_size = page_size
