from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.books_post400_response_error import BooksPost400ResponseError
from openapi_server import util

from openapi_server.models.books_post400_response_error import BooksPost400ResponseError  # noqa: E501

class BooksPost400Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, error=None):  # noqa: E501
        """BooksPost400Response - a model defined in OpenAPI

        :param status: The status of this BooksPost400Response.  # noqa: E501
        :type status: float
        :param error: The error of this BooksPost400Response.  # noqa: E501
        :type error: BooksPost400ResponseError
        """
        self.openapi_types = {
            'status': float,
            'error': BooksPost400ResponseError
        }

        self.attribute_map = {
            'status': 'status',
            'error': 'error'
        }

        self._status = status
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'BooksPost400Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _books_post_400_response of this BooksPost400Response.  # noqa: E501
        :rtype: BooksPost400Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> float:
        """Gets the status of this BooksPost400Response.


        :return: The status of this BooksPost400Response.
        :rtype: float
        """
        return self._status

    @status.setter
    def status(self, status: float):
        """Sets the status of this BooksPost400Response.


        :param status: The status of this BooksPost400Response.
        :type status: float
        """

        self._status = status

    @property
    def error(self) -> BooksPost400ResponseError:
        """Gets the error of this BooksPost400Response.


        :return: The error of this BooksPost400Response.
        :rtype: BooksPost400ResponseError
        """
        return self._error

    @error.setter
    def error(self, error: BooksPost400ResponseError):
        """Sets the error of this BooksPost400Response.


        :param error: The error of this BooksPost400Response.
        :type error: BooksPost400ResponseError
        """

        self._error = error
