from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.books_book_id_get404_response_error import BooksBookIdGet404ResponseError
from openapi_server import util

from openapi_server.models.books_book_id_get404_response_error import BooksBookIdGet404ResponseError  # noqa: E501

class BooksBookIdGet404Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, error=None):  # noqa: E501
        """BooksBookIdGet404Response - a model defined in OpenAPI

        :param error: The error of this BooksBookIdGet404Response.  # noqa: E501
        :type error: BooksBookIdGet404ResponseError
        """
        self.openapi_types = {
            'error': BooksBookIdGet404ResponseError
        }

        self.attribute_map = {
            'error': 'error'
        }

        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'BooksBookIdGet404Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _books__bookId__get_404_response of this BooksBookIdGet404Response.  # noqa: E501
        :rtype: BooksBookIdGet404Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self) -> BooksBookIdGet404ResponseError:
        """Gets the error of this BooksBookIdGet404Response.


        :return: The error of this BooksBookIdGet404Response.
        :rtype: BooksBookIdGet404ResponseError
        """
        return self._error

    @error.setter
    def error(self, error: BooksBookIdGet404ResponseError):
        """Sets the error of this BooksBookIdGet404Response.


        :param error: The error of this BooksBookIdGet404Response.
        :type error: BooksBookIdGet404ResponseError
        """

        self._error = error
