from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.books_book_id_delete500_response_error import BooksBookIdDelete500ResponseError
from openapi_server import util

from openapi_server.models.books_book_id_delete500_response_error import BooksBookIdDelete500ResponseError  # noqa: E501

class BooksBookIdDelete500Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, error=None):  # noqa: E501
        """BooksBookIdDelete500Response - a model defined in OpenAPI

        :param error: The error of this BooksBookIdDelete500Response.  # noqa: E501
        :type error: BooksBookIdDelete500ResponseError
        """
        self.openapi_types = {
            'error': BooksBookIdDelete500ResponseError
        }

        self.attribute_map = {
            'error': 'error'
        }

        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'BooksBookIdDelete500Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _books__bookId__delete_500_response of this BooksBookIdDelete500Response.  # noqa: E501
        :rtype: BooksBookIdDelete500Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self) -> BooksBookIdDelete500ResponseError:
        """Gets the error of this BooksBookIdDelete500Response.


        :return: The error of this BooksBookIdDelete500Response.
        :rtype: BooksBookIdDelete500ResponseError
        """
        return self._error

    @error.setter
    def error(self, error: BooksBookIdDelete500ResponseError):
        """Sets the error of this BooksBookIdDelete500Response.


        :param error: The error of this BooksBookIdDelete500Response.
        :type error: BooksBookIdDelete500ResponseError
        """

        self._error = error
