from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.books_book_id_put400_response_error import BooksBookIdPut400ResponseError
from openapi_server import util

from openapi_server.models.books_book_id_put400_response_error import BooksBookIdPut400ResponseError  # noqa: E501

class BooksBookIdPut400Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, error=None):  # noqa: E501
        """BooksBookIdPut400Response - a model defined in OpenAPI

        :param error: The error of this BooksBookIdPut400Response.  # noqa: E501
        :type error: BooksBookIdPut400ResponseError
        """
        self.openapi_types = {
            'error': BooksBookIdPut400ResponseError
        }

        self.attribute_map = {
            'error': 'error'
        }

        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'BooksBookIdPut400Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _books__bookId__put_400_response of this BooksBookIdPut400Response.  # noqa: E501
        :rtype: BooksBookIdPut400Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self) -> BooksBookIdPut400ResponseError:
        """Gets the error of this BooksBookIdPut400Response.


        :return: The error of this BooksBookIdPut400Response.
        :rtype: BooksBookIdPut400ResponseError
        """
        return self._error

    @error.setter
    def error(self, error: BooksBookIdPut400ResponseError):
        """Sets the error of this BooksBookIdPut400Response.


        :param error: The error of this BooksBookIdPut400Response.
        :type error: BooksBookIdPut400ResponseError
        """

        self._error = error
