from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.books_get500_response_error import BooksGet500ResponseError
from openapi_server import util

from openapi_server.models.books_get500_response_error import BooksGet500ResponseError  # noqa: E501

class BooksGet500Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, error=None):  # noqa: E501
        """BooksGet500Response - a model defined in OpenAPI

        :param error: The error of this BooksGet500Response.  # noqa: E501
        :type error: BooksGet500ResponseError
        """
        self.openapi_types = {
            'error': BooksGet500ResponseError
        }

        self.attribute_map = {
            'error': 'error'
        }

        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'BooksGet500Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _books_get_500_response of this BooksGet500Response.  # noqa: E501
        :rtype: BooksGet500Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self) -> BooksGet500ResponseError:
        """Gets the error of this BooksGet500Response.


        :return: The error of this BooksGet500Response.
        :rtype: BooksGet500ResponseError
        """
        return self._error

    @error.setter
    def error(self, error: BooksGet500ResponseError):
        """Sets the error of this BooksGet500Response.


        :param error: The error of this BooksGet500Response.
        :type error: BooksGet500ResponseError
        """

        self._error = error
