from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class BooksBookIdDelete200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None):  # noqa: E501
        """BooksBookIdDelete200Response - a model defined in OpenAPI

        :param status: The status of this BooksBookIdDelete200Response.  # noqa: E501
        :type status: float
        """
        self.openapi_types = {
            'status': float
        }

        self.attribute_map = {
            'status': 'status'
        }

        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'BooksBookIdDelete200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _books__bookId__delete_200_response of this BooksBookIdDelete200Response.  # noqa: E501
        :rtype: BooksBookIdDelete200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> float:
        """Gets the status of this BooksBookIdDelete200Response.


        :return: The status of this BooksBookIdDelete200Response.
        :rtype: float
        """
        return self._status

    @status.setter
    def status(self, status: float):
        """Sets the status of this BooksBookIdDelete200Response.


        :param status: The status of this BooksBookIdDelete200Response.
        :type status: float
        """

        self._status = status
