from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.books_get200_response_data_books_inner import BooksGet200ResponseDataBooksInner
from openapi_server import util

from openapi_server.models.books_get200_response_data_books_inner import BooksGet200ResponseDataBooksInner  # noqa: E501

class BooksPost201Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, data=None):  # noqa: E501
        """BooksPost201Response - a model defined in OpenAPI

        :param status: The status of this BooksPost201Response.  # noqa: E501
        :type status: float
        :param data: The data of this BooksPost201Response.  # noqa: E501
        :type data: BooksGet200ResponseDataBooksInner
        """
        self.openapi_types = {
            'status': float,
            'data': BooksGet200ResponseDataBooksInner
        }

        self.attribute_map = {
            'status': 'status',
            'data': 'data'
        }

        self._status = status
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'BooksPost201Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _books_post_201_response of this BooksPost201Response.  # noqa: E501
        :rtype: BooksPost201Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> float:
        """Gets the status of this BooksPost201Response.


        :return: The status of this BooksPost201Response.
        :rtype: float
        """
        return self._status

    @status.setter
    def status(self, status: float):
        """Sets the status of this BooksPost201Response.


        :param status: The status of this BooksPost201Response.
        :type status: float
        """

        self._status = status

    @property
    def data(self) -> BooksGet200ResponseDataBooksInner:
        """Gets the data of this BooksPost201Response.


        :return: The data of this BooksPost201Response.
        :rtype: BooksGet200ResponseDataBooksInner
        """
        return self._data

    @data.setter
    def data(self, data: BooksGet200ResponseDataBooksInner):
        """Sets the data of this BooksPost201Response.


        :param data: The data of this BooksPost201Response.
        :type data: BooksGet200ResponseDataBooksInner
        """

        self._data = data
