from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.books_get200_response_data_books_inner import BooksGet200ResponseDataBooksInner
from openapi_server.models.books_get200_response_data_page import BooksGet200ResponseDataPage
from openapi_server import util

from openapi_server.models.books_get200_response_data_books_inner import BooksGet200ResponseDataBooksInner  # noqa: E501
from openapi_server.models.books_get200_response_data_page import BooksGet200ResponseDataPage  # noqa: E501

class BooksGet200ResponseData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, books=None, page=None):  # noqa: E501
        """BooksGet200ResponseData - a model defined in OpenAPI

        :param books: The books of this BooksGet200ResponseData.  # noqa: E501
        :type books: List[BooksGet200ResponseDataBooksInner]
        :param page: The page of this BooksGet200ResponseData.  # noqa: E501
        :type page: BooksGet200ResponseDataPage
        """
        self.openapi_types = {
            'books': List[BooksGet200ResponseDataBooksInner],
            'page': BooksGet200ResponseDataPage
        }

        self.attribute_map = {
            'books': 'books',
            'page': 'page'
        }

        self._books = books
        self._page = page

    @classmethod
    def from_dict(cls, dikt) -> 'BooksGet200ResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _books_get_200_response_data of this BooksGet200ResponseData.  # noqa: E501
        :rtype: BooksGet200ResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def books(self) -> List[BooksGet200ResponseDataBooksInner]:
        """Gets the books of this BooksGet200ResponseData.


        :return: The books of this BooksGet200ResponseData.
        :rtype: List[BooksGet200ResponseDataBooksInner]
        """
        return self._books

    @books.setter
    def books(self, books: List[BooksGet200ResponseDataBooksInner]):
        """Sets the books of this BooksGet200ResponseData.


        :param books: The books of this BooksGet200ResponseData.
        :type books: List[BooksGet200ResponseDataBooksInner]
        """

        self._books = books

    @property
    def page(self) -> BooksGet200ResponseDataPage:
        """Gets the page of this BooksGet200ResponseData.


        :return: The page of this BooksGet200ResponseData.
        :rtype: BooksGet200ResponseDataPage
        """
        return self._page

    @page.setter
    def page(self, page: BooksGet200ResponseDataPage):
        """Sets the page of this BooksGet200ResponseData.


        :param page: The page of this BooksGet200ResponseData.
        :type page: BooksGet200ResponseDataPage
        """

        self._page = page
